# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: reposirory checkout
        uses: actions/checkout@v3
        
      - name: go setup
        uses: actions/checkout@v3
        with:
          go-version: '1.23.5'

      - name: install golangci-lint
        run: |
          curl -sSFL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.0

      - name: run linter
        run: golangci-lint run

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
